In [2]:
import pandas as pd

In [8]:
data = pd.DataFrame(data={'first':[2,3], 'second':[3,4]})

In [14]:
data['third'] = (5,6)

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
first     2 non-null int64
second    2 non-null int64
third     2 non-null int64
dtypes: int64(3)
memory usage: 128.0 bytes


In [16]:
data.shape

(2, 3)

In [20]:
import numpy as np
ar = np.array([[2,3],[4,5]])

In [26]:
np.linalg.norm(ar[1])

6.4031242374328485

In [33]:
import scipy
import scipy.spatial.distance

In [31]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

In [35]:
scipy.spatial.distance.cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

array([[ 7.,  6.,  1.],
       [ 4.,  3.,  4.],
       [ 4.,  5., 12.]])

In [37]:
scipy.spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[14.2126704]])

In [42]:
d = np.ones((10, 10))
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
b = np.eye(2, 3)
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [49]:
c = np.eye(4, 5)
np.linalg.eig()

array([0., 1.])

In [44]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [45]:
np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

ValueError: only 2 non-keyword arguments accepted