In [1]:
import numpy as np
x = np.arange(0, 2, 1)
y = np.arange(10, 12, 1)

In [2]:
x

array([0, 1])

In [3]:
y

array([10, 11])

In [4]:
x, y =np.meshgrid(x,y)

In [5]:
x.shape

(2, 2)

In [6]:
y.shape

(2, 2)

In [7]:
x

array([[0, 1],
       [0, 1]])

In [8]:
y

array([[10, 10],
       [11, 11]])

In [9]:
w0 = np.linspace(-1, 1, 50)
w1 = np.linspace(0, 100, 100)
W0, W1 = np.meshgrid(w0, w1)

In [10]:
W0.shape

(100, 50)

In [11]:
W1.shape

(100, 50)